language: java
jdk:
- openjdk11
branches:
  only:
  - develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
after_success:
- "./gradlew jacocoTestReport coveralls"
notification:
  slack:
    secure: TnACY1KgKXyVjkBHyDaR65zsboBeUE1myeqBaQDORrCXhNe4s6/GsB8T9FP3Qi1uUY/PRPLGTLOfKbFuTSxSuigQeGeNlDmaYXCc9tBlHEw7bQPDA9AyiTQdw7Ee0/m03fqQPPpIo+fw3LdHhkxgYcKqyNw+RMfuvRb697v7/D83Cn7duM03eT/DGLartJ3zszlfJfpMUQ8q6CAGm5r/XEss7Hi1YLOPvNEi9xI9kJWrSxsX3OEy0s1yS321tqwUnu2WG2CrvwqmclX6xEIMe7IzLOnP/0Rnc2EcsEJMNbHo6fMedGUG8+RZ39m5ZhQOpytD0VyR1Ph/gBE7S+ymeernEgK9FWRKeTv8Bf6/cdk1qvTodalNSBO1xx6lm93ndLjp2qmOrV6+Lw/Ef+2U8WqufMF4YYn3q2qh2Q4xE8cPTq9C0PzrgkgHJlU3YcYYvKmacFHsp+eyAlhDNAWJzf4BB0wr6WxionY5QUti2zn8yUQheeaNN8AmEKziopCqjjLL9LlXg+DICv2K+8Qb8UlHBqEeyt+3vP3JRJVuzrQ8T6WYAN3Wdnf+p0rJCaI8HAlKyoFr9DTjkG9ozQTt70F3reyKUYjzE705JQWUbu4pLlfHkqeqtwbjK0OOAVu6RHxHFNVtNqqEwmyzEwcXyVnTpcp0nExFeD/wSaWjMMY=
