language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notification:
  slack:
    secure: M5mz1zj3CeF/20PXAWaTGiXNrYxwWiFcnxq7P1EBz0cwVUMxcjaDNYFUsOXkKHwZziF5GJPfaN/LuM3xYOhwAmElg9L/9xtxpDIBcVfk4xMEMuKWj53uE2z2eXxk7j8MlPTX4NSnLXJnOiNfyzBg4h/PV7vIOM3EGDfyHQ544hVKvViAm4gvL9kl28Y0k4N8eANP5IG1u0pBKFS4t+0/t3vTBcMc774koMFbE4Q8RYq5FzheOxI3CTURqVlzUGsCenftahZDe92yGFs2ZxFHKrEzIb5w+15STvzQ14Bi2yoD4eBzwFIZ6cRgLjyYVOQkoF2kYFG2H6dxYqbCOi6Ra3hi/aneoKa6g4fg53LWOM7Uqc9E7cthNiMkI2YX6afWSr8K0bM+kAU7r974w8ExKbB1BCbX8oaK7aYwPDVCCUhbdT/X73j47gyl8yJmUZn/i2xRelvVUC+y/+4/x6X5FpebpadXTSi8vy0RIabzJrKTzj/Lh4zbFevf4W7hjNUi2ALtfnRWP9Huru3wE0+J98O4Ke0unaxDLIB40T3brpyPpFLPOkBMd78qdryd+vZS7FVM1tEpi4ASiPZERm7eDiB2Ze5S+WNg6x6rcc5ELcTozbJN9gCPMb+o0+8IJ7e4IhyRL7S7EdgqFmoShYslujwOBY2vxYEMA8mY6z7TYhg=
