language: java
jdk:
- openjdk11
branches:
  only:
  - develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
after_success:
  coveralls
notifications:
  slack: pear-ldh1042:mCNcIVNrZs0gIBnTWbi2Sf4C