language: java
jdk:
- openjdk11
branches:
  only:
  - develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
after_success:
- "./gradlew jacocoTestReport coveralls"
notification:
  slack:
    secure: TPQyaB88fBcNQcSyxUMW72TowEs0Sjh/HJlkYbjUmLbNWfitwHa35WecdLyv9mRlyDQ4QzExLbcpH05vfJ2wd+hDZCnGg78VtuXgHaGXPTGBtcoS+dcmeF4kMzYHyWdR6WcomAvu3AjNQVrzQiqDOY8jVRigMm4v3ke+Ndq3g3A0qJKmKMN41s9q2RiRpOzFdxwpvuJI9s3zPuHT6o+/Lq8Apd7zqvSAVoTRWxss4n0YO6MuW/UEFEi7kQCxK++rPnDeCNqWTU06AfI2f+M49fV0eGMlA87gppkaFCsh2QybFAhvuVnpx9VzlZQ1QYbAd7SC8LGTgk0BcgsbfEp6DAxVG8WpN2bzUmdrqCknyQprPcU4w5rfS7Qf8XOlDkqPQVh0i72PnM47x9zwCZ1aFHeSkxfTusn6L6ULV7otZ8F39EtiAaG5a0QjEExdlsISM5PmLsr2yJBVHRinioTyXPCJRrrs6XmB9r/4N5OBzSSRqizR83o3InLh6UwqJBXZRrVoMKJsYZSHulnIf21j9USZ8G6qyRbNTiAtm95MNdgCRU6oJXvT6fJC45x8UDmhnAv3Ca3yZ1lO1iPeYIAd7h9cIS6VKtF6hQOFdZw4KMe00NLKdZtHKleZb8zSBVr35K/ZCrORB7L4vlaRPliQtfFKZJjv7MRs8T9/zY6sCW4=
